

export const ArrayPreviewAnime = [
    {
        "nome": "Bocchi The Rock",
        "sinopse": "A história acompanha Hitori Gotou, uma garota sem amigos que está aprendendo a tocar guitarra para se tornar uma estrela do rock, mas é extremamente tímida. Por mais que seu sonho parecesse inalcançável, ela acaba por conhecer Nijika Ijichi, uma baterista que está a procura de uma guitarrista para sua banda, criando assim a oportunidade para Hitori entrar no mundo da música.",
        "imagemPC": "https://images7.alphacoders.com/129/1296046.jpg",
        "imagemCL": "https://images7.alphacoders.com/132/1323120.png",
    },
    {
        "nome": "Oshi no Ko",
        "sinopse": "A história de Oshi no Ko acompanha, inicialmente, Gorou Honda, um ginecologista de um hospital na zona rural do Japão, que é um grande fã da idol Ai Hoshino. Ele fica perplexo quando a artista pausa a carreira, e mais ainda quando ela aparece em seu local de trabalho, grávida.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2023/06/ai-hoshino-idol-oshi-no-ko-thumb.jpg",
        "imagemCL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi_RXg3iilxIifhn4ENHc5glmh8HiTeiTM3A&s",
    },
    {
        "nome": "Youkoso",
        "sinopse": " A história de um garoto misterioso entra em um colégio de elite com sistema de ranks das classes e alunos. Mas embora não chame muita atenção, ele é muito mais do que parece.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/8a/8a32b6a93ee5f980398ca1c89c5abdc5.jpeg",
        "imagemCL": "https://c4.wallpaperflare.com/wallpaper/691/648/922/anime-anime-girls-picture-in-picture-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-horikita-suzune-hd-wallpaper-preview.jpg",
    },
    {
        "nome": "Isekai de Cheat Skill",
        "sinopse": "Por muitos anos Tenjo Yuuya sofreu com bullying pesado, até que certo dia encontrou uma porta no porão de seu avó capaz de levá-lo para outro mundo. Recebendo poderes inimagináveis e habilidades consideradas como trapaças, Yuuya passa a se aventurar nesse novo mundo, tentando deixar para trás sua vida de sofrimento e buscando ser alguém mais forte em ambas as realidades.",
        "imagemPC": "https://wallpapercave.com/wp/wp13231037.jpg",
        "imagemCL": "https://s1.zerochan.net/Isekai.de.Cheat.Skill.wo.Te.ni.Shita.Ore.wa.Genjitsu.Sekai.wo.mo.Musou.Suru%3A.Level.Up.wa.Jinsei.wo.Kaeta.600.3914522.jpg",
    },
    {
        "nome": "Konosuba",
        "sinopse": "A história acompanha Kazuma, um jovem que morre de forma humilhante após tentar salvar uma garota. Ele recebe a oportunidade de reencarnar em um novo mundo, decidindo levar a Deusa que debochou dele como “arma”. Porém, para sua surpresa, a Deusa é completamente inútil, tornando a vida de Kazuma mais complicada do que ele gostaria.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/73/73191a27b4e067af941773b9e0de9732.jpeg",
        "imagemCL": "https://wallpapercave.com/wp/wp6289793.jpg",
    },
    {
        "nome": "Kimetsu No Yaiba",
        "sinopse": "Tanjiro, um bondoso jovem que ganha a vida vendendo carvão descobre que sua família foi massacrada por um demônio. E, para piorar, Nezuko, sua irmã mais nova e única sobrevivente, também acabou transformada em um demônio.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2022/02/rengoku-and-tanjiro-fire-katana-kimetsu-no-yaiba-thumb.jpg",
        "imagemCL": "https://wallpaper.forfun.com/fetch/31/3192bf5ae48e093fd9823082964a84d7.jpeg",
    },
    {
        "nome": "Kenka Dokugaku",
        "sinopse": "O estudante magrelo do ensino médio, Hobin Yu, é o último cara que você esperaria estrelar em um canal do NewTube, que gira em torno de lutas. Depois de seguir alguns conselhos de um misterioso canal no NewTube, Hobin logo está nocauteando caras mais fortes do que ele e arrecadando mais dinheiro do que jamais poderia ter sonhado.",
        "imagemPC": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
        "imagemCL": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
    },
];

export const ArrayInfoAnimes = {
    "Youkoso": {
        "image_capa": "../midias/image/Youkoso/image_capa.jpg",
        "nome_capa": "Youkoso",
        "nome_anime": "Nome: Youkoso",
        "estrou": "Estreou: Verão de 2017",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Drama , Suspense",
        "temas": "Temas: Psicológico , Escolar",
        "produtores": "Produtores: Studio Hibari , Lantis , AT-X , Sony Music Communications , Toranoana , Crunchyroll , Kadokawa Media House , Kadokawa , AKABEiSOFT2",
        "Estudios": "Estúdios: Lerche",
        "titulo": "Classroom of the Elite",
        "sinopse": "Classroom of the Elite é um anime ambientado na Escola de Educação Avançada, onde os alunos são classificados por pontos que determinam seu status. Kiyotaka Ayanokōji, um estudante aparentemente mediano da Classe D, esconde uma inteligência extraordinária. Cada classe compete para subir no ranking e ganhar privilégios.<br><br>À medida que Kiyotaka interage com Suzune Horikita e Kikyo Kushida, ele se envolve nas complexas dinâmicas sociais e estratégias para elevar a Classe D. Relutante no início, Kiyotaka revela suas verdadeiras capacidades e um passado misterioso, explorando temas de meritocracia, manipulação e a natureza da elite.",
        "score": "7.85",
        "users": "819.328 users",
        "image_protagonista": "../midias/image/Youkoso/image_prota.jpeg",
        "nome_protagonista": "Ayanokouji",
        "texto_protagonista": 'Kiyotaka Ayanokouji é o enigmático protagonista de "Classroom of the Elite". Estudante do prestigioso Colégio Koudo Ikusei, ele esconde suas habilidades extraordinárias e inteligência sob uma fachada de aluno mediano. Treinado na secreta "Sala Branca", Ayanokouji é um estrategista brilhante e manipulador astuto. Sua personalidade calma e reservada esconde sua verdadeira natureza e um passado misterioso, revelado aos poucos à medida que ele protege e influencia seus colegas de classe.',
    },
    "Kimetsu No Yaiba": {
        "image_capa": "../midias/image/Kimetsu no Yaiba/image_capa.jpeg",
        "nome_capa": "Kimetsu",
        "nome_anime": "Nome: Demons Slayer",
        "estrou": "Estreou: Primavera de 2019",
        "fonte": "Fonte: Mangá",
        "genero": "Gêneros: Ação , Premiado , Fantasia",
        "temas": "Temas: Histórico",
        "produtores": "Produtores: Aniplex , Shueisha",
        "Estúdios": "Estúdios: ufotable",
        "titulo": "Kimetsu no Yaiba",
        "sinopse": 'Demon Slayer é um anime ambientado no Japão Taisho, onde demônios atacam humanos. Tanjiro Kamado, um jovem bondoso, encontra sua família massacrada e sua irmã Nezuko transformada em demônio. Determinado a salvá-la, Tanjiro se junta ao Corpo de Caçadores de Demônios.<br><br>Ao longo de sua jornada, Tanjiro treina intensamente e encontra aliados como Zenitsu e Inosuke. Eles enfrentam demônios poderosos e o temível Muzan Kibutsuji. A série explora temas de família, sacrifício e a luta entre o bem e o mal, enquanto Tanjiro busca uma cura para Nezuko e justiça para sua família.',
        "score": "8.46",
        "users": "2.127.817 users",
        "image_protagonista": "../midias/image/Kimetsu no Yaiba/image_prota.jpeg",
        "nome_protagonista": "Tanjiro",
        "texto_protagonista": 'Tanjiro Kamado é o corajoso protagonista de "Demon Slayer". Criado em uma família humilde nas montanhas, ele se torna um caçador de demônios após sua família ser massacrada, exceto sua irmã Nezuko, que se transforma em um demônio. Determinado a encontrar uma cura para Nezuko e vingar sua família, Tanjiro entra no Corpo de Caçadores de Demônios. Ele é conhecido por sua bondade, determinação e um forte senso de justiça. Treinado em técnicas de respiração e combate, Tanjiro é um guerreiro habilidoso e resiliente, enfrentando desafios formidáveis enquanto mantém sua compaixão e humanidade.',
    },
}
