

export const ArrayPreviewAnime = [
    {
        "nome": "Bocchi The Rock",
        "sinopse": "A história acompanha Hitori Gotou, uma garota sem amigos que está aprendendo a tocar guitarra para se tornar uma estrela do rock, mas é extremamente tímida. Por mais que seu sonho parecesse inalcançável, ela acaba por conhecer Nijika Ijichi, uma baterista que está a procura de uma guitarrista para sua banda, criando assim a oportunidade para Hitori entrar no mundo da música.",
        "imagemPC": "https://images7.alphacoders.com/129/1296046.jpg",
        "imagemCL": "https://images7.alphacoders.com/132/1323120.png",
    },
    {
        "nome": "Oshi no Ko",
        "sinopse": "A história de Oshi no Ko acompanha, inicialmente, Gorou Honda, um ginecologista de um hospital na zona rural do Japão, que é um grande fã da idol Ai Hoshino. Ele fica perplexo quando a artista pausa a carreira, e mais ainda quando ela aparece em seu local de trabalho, grávida.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2023/06/ai-hoshino-idol-oshi-no-ko-thumb.jpg",
        "imagemCL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi_RXg3iilxIifhn4ENHc5glmh8HiTeiTM3A&s",
    },
    {
        "nome": "Youkoso",
        "sinopse": " A história de um garoto misterioso entra em um colégio de elite com sistema de ranks das classes e alunos. Mas embora não chame muita atenção, ele é muito mais do que parece.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/8a/8a32b6a93ee5f980398ca1c89c5abdc5.jpeg",
        "imagemCL": "https://c4.wallpaperflare.com/wallpaper/691/648/922/anime-anime-girls-picture-in-picture-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-horikita-suzune-hd-wallpaper-preview.jpg",
    },
    {
        "nome": "Isekai de Cheat Skill",
        "sinopse": "Por muitos anos Tenjo Yuuya sofreu com bullying pesado, até que certo dia encontrou uma porta no porão de seu avó capaz de levá-lo para outro mundo. Recebendo poderes inimagináveis e habilidades consideradas como trapaças, Yuuya passa a se aventurar nesse novo mundo, tentando deixar para trás sua vida de sofrimento e buscando ser alguém mais forte em ambas as realidades.",
        "imagemPC": "https://wallpapercave.com/wp/wp13231037.jpg",
        "imagemCL": "https://s1.zerochan.net/Isekai.de.Cheat.Skill.wo.Te.ni.Shita.Ore.wa.Genjitsu.Sekai.wo.mo.Musou.Suru%3A.Level.Up.wa.Jinsei.wo.Kaeta.600.3914522.jpg",
    },
    {
        "nome": "Konosuba",
        "sinopse": "A história acompanha Kazuma, um jovem que morre de forma humilhante após tentar salvar uma garota. Ele recebe a oportunidade de reencarnar em um novo mundo, decidindo levar a Deusa que debochou dele como “arma”. Porém, para sua surpresa, a Deusa é completamente inútil, tornando a vida de Kazuma mais complicada do que ele gostaria.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/73/73191a27b4e067af941773b9e0de9732.jpeg",
        "imagemCL": "https://wallpapercave.com/wp/wp6289793.jpg",
    },
    {
        "nome": "Kimetsu No Yaiba",
        "sinopse": "Tanjiro, um bondoso jovem que ganha a vida vendendo carvão descobre que sua família foi massacrada por um demônio. E, para piorar, Nezuko, sua irmã mais nova e única sobrevivente, também acabou transformada em um demônio.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2022/02/rengoku-and-tanjiro-fire-katana-kimetsu-no-yaiba-thumb.jpg",
        "imagemCL": "https://wallpaper.forfun.com/fetch/31/3192bf5ae48e093fd9823082964a84d7.jpeg",
    },
    {
        "nome": "Kenka Dokugaku",
        "sinopse": "O estudante magrelo do ensino médio, Hobin Yu, é o último cara que você esperaria estrelar em um canal do NewTube, que gira em torno de lutas. Depois de seguir alguns conselhos de um misterioso canal no NewTube, Hobin logo está nocauteando caras mais fortes do que ele e arrecadando mais dinheiro do que jamais poderia ter sonhado.",
        "imagemPC": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
        "imagemCL": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
    },
];

export const ArrayInfoAnimes = {
    "Youkoso": {
        "image_capa": "midias/image/Youkoso/image_capa.jpg",
        "nome_capa": "Youkoso",
        "nome_anime": "Nome: Youkoso",
        "estrou": "Estreou: Verão de 2017",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Drama , Suspense",
        "temas": "Temas: Psicológico , Escolar",
        "produtores": "Produtores: Studio Hibari , Lantis , AT-X , Sony Music Communications , Toranoana , Crunchyroll , Kadokawa Media House , Kadokawa , AKABEiSOFT2",
        "estudios": "Estúdios: Lerche",
        "titulo": "Classroom of the Elite",
        "sinopse": "Classroom of the Elite é um anime ambientado na Escola de Educação Avançada, onde os alunos são classificados por pontos que determinam seu status. Kiyotaka Ayanokōji, um estudante aparentemente mediano da Classe D, esconde uma inteligência extraordinária. Cada classe compete para subir no ranking e ganhar privilégios.<br><br>À medida que Kiyotaka interage com Suzune Horikita e Kikyo Kushida, ele se envolve nas complexas dinâmicas sociais e estratégias para elevar a Classe D. Relutante no início, Kiyotaka revela suas verdadeiras capacidades e um passado misterioso, explorando temas de meritocracia, manipulação e a natureza da elite.",
        "score": "7.85",
        "users": "819.328 users",
        "image_protagonista": "../midias/image/Youkoso/image_prota.jpeg",
        "nome_protagonista": "Ayanokouji",
        "texto_protagonista": 'Kiyotaka Ayanokouji é o enigmático protagonista de "Classroom of the Elite". Estudante do prestigioso Colégio Koudo Ikusei, ele esconde suas habilidades extraordinárias e inteligência sob uma fachada de aluno mediano. Treinado na secreta "Sala Branca", Ayanokouji é um estrategista brilhante e manipulador astuto. Sua personalidade calma e reservada esconde sua verdadeira natureza e um passado misterioso, revelado aos poucos à medida que ele protege e influencia seus colegas de classe.',
    },
    "Kimetsu No Yaiba": {
        "image_capa": "midias/image/Kimetsu no Yaiba/image_capa.jpeg",
        "nome_capa": "Kimetsu",
        "nome_anime": "Nome: Demons Slayer",
        "estrou": "Estreou: Primavera de 2019",
        "fonte": "Fonte: Mangá",
        "genero": "Gêneros: Ação , Premiado , Fantasia",
        "temas": "Temas: Histórico",
        "produtores": "Produtores: Aniplex , Shueisha",
        "estudios": "Estúdios: ufotable",
        "titulo": "Kimetsu no Yaiba",
        "sinopse": 'Demon Slayer é um anime ambientado no Japão Taisho, onde demônios atacam humanos. Tanjiro Kamado, um jovem bondoso, encontra sua família massacrada e sua irmã Nezuko transformada em demônio. Determinado a salvá-la, Tanjiro se junta ao Corpo de Caçadores de Demônios.<br><br>Ao longo de sua jornada, Tanjiro treina intensamente e encontra aliados como Zenitsu e Inosuke. Eles enfrentam demônios poderosos e o temível Muzan Kibutsuji. A série explora temas de família, sacrifício e a luta entre o bem e o mal, enquanto Tanjiro busca uma cura para Nezuko e justiça para sua família.',
        "score": "8.46",
        "users": "2.127.817 users",
        "image_protagonista": "../midias/image/Kimetsu no Yaiba/image_prota.jpeg",
        "nome_protagonista": "Tanjiro Kamado",
        "texto_protagonista": 'Tanjiro Kamado é o protagonista de "Demon Slayer". Criado nas montanhas, ele se torna um caçador de demônios após sua família ser massacrada, exceto sua irmã Nezuko, que vira um demônio. Determinado a curar Nezuko e vingar sua família, Tanjiro entra na organização de Caçadores de Demônios. Conhecido por sua bondade e justiça, ele é treinado em técnicas de respiração e combate. Tanjiro enfrenta desafios formidáveis, mantendo sua compaixão e humanidade.',
    },
    "Bocchi The Rock": {
        "image_capa": "midias/image/Bocchi-the-rock/image_capa.png",
        "nome_capa": "Bocchi",
        "nome_anime": "Nome: Bocchi The Rock",
        "estrou": "Estreou: Outono de 2022",
        "fonte": "Fonte: 4-koma manga",
        "genero": "Gêneros: Comédia",
        "temas": "Temas: CGDCT , Música",
        "produtores": "Produtores: Aniplex , Houbunsha",
        "estudios": "Estúdios: CloverWorks",
        "titulo": "Bocchi The Rock",
        "sinopse": '"Bocchi the Rock!" é um anime que segue Hitori Gotou, uma estudante tímida e introvertida, apaixonada por tocar guitarra. Ela sonha em formar uma banda, mas sua ansiedade social dificulta suas interações. Um dia, Nijika Ijichi, uma extrovertida baterista, convida Hitori para sua banda, Kessoku Band.<br><br>Enquanto Hitori se junta à banda, ela começa a enfrentar seus medos e a fazer novas amizades. Juntas, elas trabalham para superar desafios pessoais e musicais, com Hitori lentamente saindo de sua concha. A série aborda temas de amizade, crescimento pessoal e a busca pela realização de sonhos.',
        "score": "8.78",
        "users": "360.817 users",
        "image_protagonista": "../midias/image/Bocchi-the-rock/image_prota.jpeg",
        "nome_protagonista": "Gotoh Hitori",
        "texto_protagonista": 'Gotoh Hitori é a tímida protagonista de "Bocchi the Rock!". Ela tem uma paixão profunda por tocar guitarra, mas sua ansiedade social a impede de se destacar. Isolada e introvertida, Hitori pratica sozinha em seu quarto, sonhando em se juntar a uma banda. Um encontro casual com uma baterista extrovertida, muda seu destino. Hitori se junta à Kessoku Band e começa a enfrentar seus medos, revelando um talento impressionante e uma determinação que inspira aqueles ao seu redor.',
    },
    "Oshi no Ko": {
        "image_capa": "midias/image/Oshi no ko/image_capa.jpeg",
        "nome_capa": "Oshi no Ko",
        "nome_anime": "Nome: Oshi no Ko",
        "estrou": "Estreou: Primavera de 2023",
        "fonte": "Fonte: Mangá",
        "genero": "Gêneros: Premiado , Drama , Sobrenatural",
        "temas": "Temas: Reencarnação , Showbiz",
        "produtores": "Produtores: Delfi Sound, Shueisha, CyberAgent, Kadokawa",
        "estudios": "Estúdios: Doga Kobo",
        "titulo": "Oshi no Ko",
        "sinopse": '"Oshi no Ko" é um anime que explora o mundo do entretenimento japonês através da história de Ai Hoshino, uma idol que dá à luz gêmeos em segredo. Esses gêmeos são reencarnações de um médico e sua paciente, ambos fãs de Ai. Eles enfrentam os desafios da fama enquanto tentam proteger sua mãe e descobrir segredos obscuros da indústria.<br><br>O anime revela as realidades cruéis da fama e os sacrifícios envolvidos, explorando temas de obsessão e poder. A jornada dos gêmeos oferece uma visão profunda sobre o brilho e as sombras do mundo do entretenimento, desvendando os mistérios por trás da vida de Ai e da indústria que ela representa.',
        "score": "8.63",
        "users": "484.486 users",
        "image_protagonista": "../midias/image/Oshi no ko/image_prota.jpeg",
        "nome_protagonista": "Aqua Hoshino",
        "texto_protagonista": 'Aqua Hoshino, um dos gêmeos de Ai Hoshino, reencarna como um jovem com a memória de sua vida passada como médico. Determinado a proteger sua mãe e enfrentar os desafios da indústria do entretenimento, Aqua usa sua inteligência e habilidades estratégicas para lidar com as complexidades do show business. Sua busca por justiça e compreensão o torna um personagem central na trama.',
    }, 
    "Konosuba": {
        "image_capa": "midias/image/Konosuba/image_capa.jpg",
        "nome_capa": "Konosuba",
        "nome_anime": "Nome: Konosuba",
        "estrou": "Estreou: Inverno de 2016",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Aventura , Comédia , Fantasia",
        "temas": "Temas: Isekai , Paródia",
        "produtores": "Produtores: Half HP Studio , Nippon Columbia , KlockWorx , Sony Music Communications , Toranoana , 81 Produce , Kadokawa",
        "estudios": "Estúdios: Studio Deen",
        "titulo": "Kono Subarashii Sekai ni Shukufuku wo!",
        "sinopse": '"KonoSuba" segue Kazuma Satou, que, após morrer, é reincarnado em um mundo de fantasia para derrotar o Senhor das Trevas. Ele escolhe a deusa Aqua como companheira, mas logo descobre que ela é mais um problema do que uma ajuda. Juntos, enfrentam desventuras e desafios enquanto tentam cumprir sua missão de maneira inesperada e cômica.<br><br>Kazuma, Aqua, e os excêntricos Megumin e Darkness enfrentam situações absurdas e inimigos bizarramente poderosos, explorando temas de aventura e comédia em um mundo de fantasia repleto de humor.',
        "score": "8.10",
        "users": "1.291.762 users",
        "image_protagonista": "../midias/image/Konosuba/image_prota.jpeg",
        "nome_protagonista": "Kazuma",
        "texto_protagonista": 'Kazuma Satou é o protagonista de "KonoSuba". Reencarnado em um mundo de fantasia, ele deve derrotar o Senhor das Trevas. Escolhendo a deusa Aqua como companheira, Kazuma lida com uma série de desventuras ao lado dela e dos excêntricos Megumin e Darkness. Sua abordagem pragmática e sentido de humor o tornam um herói improvável em um mundo de fantasia.',
    },
    "Isekai de Cheat Skill": {
        "image_capa": "midias/image/Isekai the cheat skill/image_capa.jpg",
        "nome_capa": "Cheat skill",
        "nome_anime": "Nome: Isekai de Cheat Skill",
        "estrou": "Estreou: Primavera de 2023",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Ação , Aventura , Fantasia",
        "temas": "Temas: Isekai , Escola",
        "produtores": "Produtores: TMS Entertainment , Tokyo MX , BS11 , Kadokawa , CTW",
        "estudios": "Estúdios: Millepensee",
        "titulo": "Isekai de Cheat Skill",
        "sinopse": '"Isekai de Cheat Skill" segue o jovem Yuya Tenjo, que é transportado para um mundo de fantasia após ser enganado e morto. No novo mundo, ele adquire habilidades de cheat que o tornam extremamente poderoso. Determinado a usar seus novos poderes para mudar sua vida, Yuya embarca em uma jornada para explorar e dominar esse universo.<br><br>Com habilidades que desafiam os limites do mundo de fantasia, Yuya enfrenta inimigos poderosos e desafios intrigantes. O anime combina aventura e ação, destacando a ascensão de Yuya enquanto ele se adapta à sua nova vida e transforma sua situação, explorando temas de poder, redenção e a busca por um novo propósito.',
        "score": "6.35",
        "users": "163.112 users",
        "image_protagonista": "../midias/image/Isekai the cheat skill/image_prota.jpeg",
        "nome_protagonista": "Yuya Tenjo",
        "texto_protagonista": 'Yuya Tenjo é o protagonista de "Isekai de Cheat Skill". Após ser transportado para um mundo de fantasia e adquirir habilidades de cheat, ele rapidamente se destaca como um dos mais poderosos do novo universo. Usando seus poderes excepcionais, Yuya enfrenta inimigos e desafios enquanto busca transformar sua vida e encontrar um novo propósito. Sua jornada é marcada por aventuras emocionantes e o desenvolvimento pessoal, revelando uma história de superação e exploração.',
    },
    "Kenka Dokugaku": {
        "image_capa": "midias/image/Kenka dokugaku/image_capa.jpeg",
        "nome_capa": "Viral Hit",
        "nome_anime": "Nome: Kenka Dokugaku",
        "estrou": "Estreou: Primavera de 2024",
        "fonte": "Fonte: Web manga",
        "genero": "Gêneros: Ação, Comédia",
        "temas": "Temas: Escola",
        "produtores": "Produtores: Dentsu , Fuji TV , GAGA , Slow Curve , Fujipacific Music , BS Fuji , Crunchyroll , Line Digital Frontier",
        "estudios": "Estúdios: Okuruto Noboru",
        "titulo": "Kenka Dokugaku",
        "sinopse": '"Viral Hit" segue Yoo Hobin, um estudante humilhado por Pakgo, um popular streamer do Newtube. Além das dificuldades na escola, Hobin trabalha duro para pagar o hospital de sua mãe. Após um acidente com o cinegrafista Jiksae, a briga entre eles se torna viral e Hobin ganha uma grande audiência.<br><br>Aproveitando a fama repentina, Hobin se une a Jiksae para produzir mais conteúdo e explorar o potencial do streaming. Juntos, enfrentam desafios e rivais como Pakgo, em busca de sucesso e superação no mundo digital.',
        "score": "7.35",
        "users": "24.313 users",
        "image_protagonista": "../midias/image/Kenka dokugaku/image_prota.jpg",
        "nome_protagonista": "Yoo Hobin",
        "texto_protagonista": 'Yoo Hobin é o protagonista de "Viral Hit". Um estudante do ensino médio que sofre com a humilhação de Pakgo, um famoso streamer, e enfrenta dificuldades financeiras enquanto trabalha para pagar o hospital de sua mãe. Sua vida muda quando uma briga acidental com o cinegrafista Jiksae se torna viral. Aproveitando a fama repentina, Hobin se junta a Jiksae para explorar o potencial do streaming no Newtube. Determinado a transformar sua sorte, Hobin busca superar rivais e alcançar sucesso no competitivo mundo digital.',
    },
}
