

export const ArrayPreviewAnime = [
    {
        "nome": "Bocchi The Rock",
        "sinopse": "A história acompanha Hitori Gotou, uma garota sem amigos que está aprendendo a tocar guitarra para se tornar uma estrela do rock, mas é extremamente tímida. Por mais que seu sonho parecesse inalcançável, ela acaba por conhecer Nijika Ijichi, uma baterista que está a procura de uma guitarrista para sua banda, criando assim a oportunidade para Hitori entrar no mundo da música.",
        "imagemPC": "https://images7.alphacoders.com/129/1296046.jpg",
        "imagemCL": "https://images7.alphacoders.com/132/1323120.png",
    },
    {
        "nome": "Oshi no Ko",
        "sinopse": "A história de Oshi no Ko acompanha, inicialmente, Gorou Honda, um ginecologista de um hospital na zona rural do Japão, que é um grande fã da idol Ai Hoshino. Ele fica perplexo quando a artista pausa a carreira, e mais ainda quando ela aparece em seu local de trabalho, grávida.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2023/06/ai-hoshino-idol-oshi-no-ko-thumb.jpg",
        "imagemCL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi_RXg3iilxIifhn4ENHc5glmh8HiTeiTM3A&s",
    },
    {
        "nome": "Youkoso",
        "sinopse": " A história de um garoto misterioso entra em um colégio de elite com sistema de ranks das classes e alunos. Mas embora não chame muita atenção, ele é muito mais do que parece.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/8a/8a32b6a93ee5f980398ca1c89c5abdc5.jpeg",
        "imagemCL": "https://c4.wallpaperflare.com/wallpaper/691/648/922/anime-anime-girls-picture-in-picture-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-horikita-suzune-hd-wallpaper-preview.jpg",
    },
    {
        "nome": "Isekai de Cheat Skill",
        "sinopse": "Por muitos anos Tenjo Yuuya sofreu com bullying pesado, até que certo dia encontrou uma porta no porão de seu avó capaz de levá-lo para outro mundo. Recebendo poderes inimagináveis e habilidades consideradas como trapaças, Yuuya passa a se aventurar nesse novo mundo, tentando deixar para trás sua vida de sofrimento e buscando ser alguém mais forte em ambas as realidades.",
        "imagemPC": "https://wallpapercave.com/wp/wp13231037.jpg",
        "imagemCL": "https://s1.zerochan.net/Isekai.de.Cheat.Skill.wo.Te.ni.Shita.Ore.wa.Genjitsu.Sekai.wo.mo.Musou.Suru%3A.Level.Up.wa.Jinsei.wo.Kaeta.600.3914522.jpg",
    },
    {
        "nome": "Konosuba",
        "sinopse": "A história acompanha Kazuma, um jovem que morre de forma humilhante após tentar salvar uma garota. Ele recebe a oportunidade de reencarnar em um novo mundo, decidindo levar a Deusa que debochou dele como “arma”. Porém, para sua surpresa, a Deusa é completamente inútil, tornando a vida de Kazuma mais complicada do que ele gostaria.",
        "imagemPC": "https://wallpaper.forfun.com/fetch/73/73191a27b4e067af941773b9e0de9732.jpeg",
        "imagemCL": "https://wallpapercave.com/wp/wp6289793.jpg",
    },
    {
        "nome": "Kimetsu No Yaiba",
        "sinopse": "Tanjiro, um bondoso jovem que ganha a vida vendendo carvão descobre que sua família foi massacrada por um demônio. E, para piorar, Nezuko, sua irmã mais nova e única sobrevivente, também acabou transformada em um demônio.",
        "imagemPC": "https://moewalls.com/wp-content/uploads/2022/02/rengoku-and-tanjiro-fire-katana-kimetsu-no-yaiba-thumb.jpg",
        "imagemCL": "https://wallpaper.forfun.com/fetch/31/3192bf5ae48e093fd9823082964a84d7.jpeg",
    },
    {
        "nome": "Kenka Dokugaku",
        "sinopse": "O estudante magrelo do ensino médio, Hobin Yu, é o último cara que você esperaria estrelar em um canal do NewTube, que gira em torno de lutas. Depois de seguir alguns conselhos de um misterioso canal no NewTube, Hobin logo está nocauteando caras mais fortes do que ele e arrecadando mais dinheiro do que jamais poderia ter sonhado.",
        "imagemPC": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
        "imagemCL": "https://pbs.twimg.com/media/GK45V32W0AEY29w.jpg",
    },
];

export const ArrayInfoAnimes = {
    "Youkoso": {
        "image_capa": "midias/image/Youkoso/image_capa.jpg",
        "nome_capa": "Youkoso",
        "nome_anime": "Nome: Youkoso",
        "estrou": "Estreou: Verão de 2017",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Drama , Suspense",
        "temas": "Temas: Psicológico , Escolar",
        "produtores": "Produtores: Studio Hibari , Lantis , AT-X , Sony Music Communications , Toranoana , Crunchyroll , Kadokawa Media House , Kadokawa , AKABEiSOFT2",
        "estudios": "Estúdios: Lerche",
        "titulo": "Classroom of the Elite",
        "sinopse": "Classroom of the Elite é um anime ambientado na Escola de Educação Avançada, onde os alunos são classificados por pontos que determinam seu status. Kiyotaka Ayanokōji, um estudante aparentemente mediano da Classe D, esconde uma inteligência extraordinária. Cada classe compete para subir no ranking e ganhar privilégios.<br><br>À medida que Kiyotaka interage com Suzune Horikita e Kikyo Kushida, ele se envolve nas complexas dinâmicas sociais e estratégias para elevar a Classe D. Relutante no início, Kiyotaka revela suas verdadeiras capacidades e um passado misterioso, explorando temas de meritocracia, manipulação e a natureza da elite.",
        "score": "7.85",
        "users": "819.328 users",
        "image_protagonista": "midias/image/Youkoso/image_prota.jpeg",
        "nome_protagonista": "Ayanokouji",
        "texto_protagonista": 'Kiyotaka Ayanokouji é o enigmático protagonista de "Classroom of the Elite". Estudante do prestigioso Colégio Koudo Ikusei, ele esconde suas habilidades extraordinárias e inteligência sob uma fachada de aluno mediano. Treinado na secreta "Sala Branca", Ayanokouji é um estrategista brilhante e manipulador astuto. Sua personalidade calma e reservada esconde sua verdadeira natureza e um passado misterioso, revelado aos poucos à medida que ele protege e influencia seus colegas de classe.',
    },
    "Kimetsu No Yaiba": {
        "image_capa": "midias/image/Kimetsu no Yaiba/image_capa.jpeg",
        "nome_capa": "Kimetsu",
        "nome_anime": "Nome: Demons Slayer",
        "estrou": "Estreou: Primavera de 2019",
        "fonte": "Fonte: Mangá",
        "genero": "Gêneros: Ação , Premiado , Fantasia",
        "temas": "Temas: Histórico",
        "produtores": "Produtores: Aniplex , Shueisha",
        "estudios": "Estúdios: ufotable",
        "titulo": "Kimetsu no Yaiba",
        "sinopse": 'Demon Slayer é um anime ambientado no Japão Taisho, onde demônios atacam humanos. Tanjiro Kamado, um jovem bondoso, encontra sua família massacrada e sua irmã Nezuko transformada em demônio. Determinado a salvá-la, Tanjiro se junta ao Corpo de Caçadores de Demônios.<br><br>Ao longo de sua jornada, Tanjiro treina intensamente e encontra aliados como Zenitsu e Inosuke. Eles enfrentam demônios poderosos e o temível Muzan Kibutsuji. A série explora temas de família, sacrifício e a luta entre o bem e o mal, enquanto Tanjiro busca uma cura para Nezuko e justiça para sua família.',
        "score": "8.46",
        "users": "2.127.817 users",
        "image_protagonista": "midias/image/Kimetsu no Yaiba/image_prota.jpeg",
        "nome_protagonista": "Tanjiro Kamado",
        "texto_protagonista": 'Tanjiro Kamado é o protagonista de "Demon Slayer". Criado nas montanhas, ele se torna um caçador de demônios após sua família ser massacrada, exceto sua irmã Nezuko, que vira um demônio. Determinado a curar Nezuko e vingar sua família, Tanjiro entra na organização de Caçadores de Demônios. Conhecido por sua bondade e justiça, ele é treinado em técnicas de respiração e combate. Tanjiro enfrenta desafios formidáveis, mantendo sua compaixão e humanidade.',
    },
    "Bocchi The Rock": {
        "image_capa": "midias/image/Bocchi-the-rock/image_capa.png",
        "nome_capa": "Bocchi",
        "nome_anime": "Nome: Bocchi The Rock",
        "estrou": "Estreou: Outono de 2022",
        "fonte": "Fonte: 4-koma manga",
        "genero": "Gêneros: Comédia",
        "temas": "Temas: CGDCT , Música",
        "produtores": "Produtores: Aniplex , Houbunsha",
        "estudios": "Estúdios: CloverWorks",
        "titulo": "Bocchi The Rock",
        "sinopse": '"Bocchi the Rock!" é um anime que segue Hitori Gotou, uma estudante tímida e introvertida, apaixonada por tocar guitarra. Ela sonha em formar uma banda, mas sua ansiedade social dificulta suas interações. Um dia, Nijika Ijichi, uma extrovertida baterista, convida Hitori para sua banda, Kessoku Band.<br><br>Enquanto Hitori se junta à banda, ela começa a enfrentar seus medos e a fazer novas amizades. Juntas, elas trabalham para superar desafios pessoais e musicais, com Hitori lentamente saindo de sua concha. A série aborda temas de amizade, crescimento pessoal e a busca pela realização de sonhos.',
        "score": "8.78",
        "users": "360.817 users",
        "image_protagonista": "midias/image/Bocchi-the-rock/image_prota.jpeg",
        "nome_protagonista": "Gotoh Hitori",
        "texto_protagonista": 'Gotoh Hitori é a tímida protagonista de "Bocchi the Rock!". Ela tem uma paixão profunda por tocar guitarra, mas sua ansiedade social a impede de se destacar. Isolada e introvertida, Hitori pratica sozinha em seu quarto, sonhando em se juntar a uma banda. Um encontro casual com uma baterista extrovertida, muda seu destino. Hitori se junta à Kessoku Band e começa a enfrentar seus medos, revelando um talento impressionante e uma determinação que inspira aqueles ao seu redor.',
    },
    "Oshi no Ko": {
        "image_capa": "midias/image/Oshi no ko/image_capa.jpeg",
        "nome_capa": "Oshi no Ko",
        "nome_anime": "Nome: Oshi no Ko",
        "estrou": "Estreou: Primavera de 2023",
        "fonte": "Fonte: Mangá",
        "genero": "Gêneros: Premiado , Drama , Sobrenatural",
        "temas": "Temas: Reencarnação , Showbiz",
        "produtores": "Produtores: Delfi Sound, Shueisha, CyberAgent, Kadokawa",
        "estudios": "Estúdios: Doga Kobo",
        "titulo": "Oshi no Ko",
        "sinopse": '"Oshi no Ko" é um anime que explora o mundo do entretenimento japonês através da história de Ai Hoshino, uma idol que dá à luz gêmeos em segredo. Esses gêmeos são reencarnações de um médico e sua paciente, ambos fãs de Ai. Eles enfrentam os desafios da fama enquanto tentam proteger sua mãe e descobrir segredos obscuros da indústria.<br><br>O anime revela as realidades cruéis da fama e os sacrifícios envolvidos, explorando temas de obsessão e poder. A jornada dos gêmeos oferece uma visão profunda sobre o brilho e as sombras do mundo do entretenimento, desvendando os mistérios por trás da vida de Ai e da indústria que ela representa.',
        "score": "8.63",
        "users": "484.486 users",
        "image_protagonista": "midias/image/Oshi no ko/image_prota.jpeg",
        "nome_protagonista": "Aqua Hoshino",
        "texto_protagonista": 'Aqua Hoshino, um dos gêmeos de Ai Hoshino, reencarna como um jovem com a memória de sua vida passada como médico. Determinado a proteger sua mãe e enfrentar os desafios da indústria do entretenimento, Aqua usa sua inteligência e habilidades estratégicas para lidar com as complexidades do show business. Sua busca por justiça e compreensão o torna um personagem central na trama.',
    }, 
    "Konosuba": {
        "image_capa": "midias/image/Konosuba/image_capa.jpg",
        "nome_capa": "Konosuba",
        "nome_anime": "Nome: Konosuba",
        "estrou": "Estreou: Inverno de 2016",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Aventura , Comédia , Fantasia",
        "temas": "Temas: Isekai , Paródia",
        "produtores": "Produtores: Half HP Studio , Nippon Columbia , KlockWorx , Sony Music Communications , Toranoana , 81 Produce , Kadokawa",
        "estudios": "Estúdios: Studio Deen",
        "titulo": "Kono Subarashii Sekai ni Shukufuku wo!",
        "sinopse": '"KonoSuba" segue Kazuma Satou, que, após morrer, é reincarnado em um mundo de fantasia para derrotar o Senhor das Trevas. Ele escolhe a deusa Aqua como companheira, mas logo descobre que ela é mais um problema do que uma ajuda. Juntos, enfrentam desventuras e desafios enquanto tentam cumprir sua missão de maneira inesperada e cômica.<br><br>Kazuma, Aqua, e os excêntricos Megumin e Darkness enfrentam situações absurdas e inimigos bizarramente poderosos, explorando temas de aventura e comédia em um mundo de fantasia repleto de humor.',
        "score": "8.10",
        "users": "1.291.762 users",
        "image_protagonista": "midias/image/Konosuba/image_prota.jpeg",
        "nome_protagonista": "Kazuma",
        "texto_protagonista": 'Kazuma Satou é o protagonista de "KonoSuba". Reencarnado em um mundo de fantasia, ele deve derrotar o Senhor das Trevas. Escolhendo a deusa Aqua como companheira, Kazuma lida com uma série de desventuras ao lado dela e dos excêntricos Megumin e Darkness. Sua abordagem pragmática e sentido de humor o tornam um herói improvável em um mundo de fantasia.',
    },
    "Isekai de Cheat Skill": {
        "image_capa": "midias/image/Isekai the cheat skill/image_capa.jpg",
        "nome_capa": "Cheat skill",
        "nome_anime": "Nome: Isekai de Cheat Skill",
        "estrou": "Estreou: Primavera de 2023",
        "fonte": "Fonte: Light novel",
        "genero": "Gêneros: Ação , Aventura , Fantasia",
        "temas": "Temas: Isekai , Escola",
        "produtores": "Produtores: TMS Entertainment , Tokyo MX , BS11 , Kadokawa , CTW",
        "estudios": "Estúdios: Millepensee",
        "titulo": "Isekai de Cheat Skill",
        "sinopse": '"Isekai de Cheat Skill" segue o jovem Yuya Tenjo, que é transportado para um mundo de fantasia após ser enganado e morto. No novo mundo, ele adquire habilidades de cheat que o tornam extremamente poderoso. Determinado a usar seus novos poderes para mudar sua vida, Yuya embarca em uma jornada para explorar e dominar esse universo.<br><br>Com habilidades que desafiam os limites do mundo de fantasia, Yuya enfrenta inimigos poderosos e desafios intrigantes. O anime combina aventura e ação, destacando a ascensão de Yuya enquanto ele se adapta à sua nova vida e transforma sua situação, explorando temas de poder, redenção e a busca por um novo propósito.',
        "score": "6.35",
        "users": "163.112 users",
        "image_protagonista": "midias/image/Isekai the cheat skill/image_prota.jpeg",
        "nome_protagonista": "Yuya Tenjo",
        "texto_protagonista": 'Yuya Tenjo é o protagonista de "Isekai de Cheat Skill". Após ser transportado para um mundo de fantasia e adquirir habilidades de cheat, ele rapidamente se destaca como um dos mais poderosos do novo universo. Usando seus poderes excepcionais, Yuya enfrenta inimigos e desafios enquanto busca transformar sua vida e encontrar um novo propósito. Sua jornada é marcada por aventuras emocionantes e o desenvolvimento pessoal, revelando uma história de superação e exploração.',
    },
    "Kenka Dokugaku": {
        "image_capa": "midias/image/Kenka dokugaku/image_capa.jpeg",
        "nome_capa": "Viral Hit",
        "nome_anime": "Nome: Kenka Dokugaku",
        "estrou": "Estreou: Primavera de 2024",
        "fonte": "Fonte: Web manga",
        "genero": "Gêneros: Ação, Comédia",
        "temas": "Temas: Escola",
        "produtores": "Produtores: Dentsu , Fuji TV , GAGA , Slow Curve , Fujipacific Music , BS Fuji , Crunchyroll , Line Digital Frontier",
        "estudios": "Estúdios: Okuruto Noboru",
        "titulo": "Kenka Dokugaku",
        "sinopse": '"Viral Hit" segue Yoo Hobin, um estudante humilhado por Pakgo, um popular streamer do Newtube. Além das dificuldades na escola, Hobin trabalha duro para pagar o hospital de sua mãe. Após um acidente com o cinegrafista Jiksae, a briga entre eles se torna viral e Hobin ganha uma grande audiência.<br><br>Aproveitando a fama repentina, Hobin se une a Jiksae para produzir mais conteúdo e explorar o potencial do streaming. Juntos, enfrentam desafios e rivais como Pakgo, em busca de sucesso e superação no mundo digital.',
        "score": "7.35",
        "users": "24.313 users",
        "image_protagonista": "midias/image/Kenka dokugaku/image_prota.jpg",
        "nome_protagonista": "Yoo Hobin",
        "texto_protagonista": 'Yoo Hobin é o protagonista de "Viral Hit". Um estudante do ensino médio que sofre com a humilhação de Pakgo, um famoso streamer, e enfrenta dificuldades financeiras enquanto trabalha para pagar o hospital de sua mãe. Sua vida muda quando uma briga acidental com o cinegrafista Jiksae se torna viral. Aproveitando a fama repentina, Hobin se junta a Jiksae para explorar o potencial do streaming no Newtube. Determinado a transformar sua sorte, Hobin busca superar rivais e alcançar sucesso no competitivo mundo digital.',
    },
}

export const ArrayInfoPersonagens = {
    "Youkoso": {
        "nome_personagem": ['Ayanokouji', 'Horikita', 'Kushida', 'Karuizawa'],
        "img_personagem": [
            "midias/image/Youkoso/Kiyotaka_Ayanokōji.png",
            "midias/image/Youkoso/Suzune_Horikita.png",
            "midias/image/Youkoso/Kikyō_Kushida.png",
            "midias/image/Youkoso/Kei_Karuizawa.png"
        ],
        "texto_personagem": [
            'Kiyotaka Ayanokouji é o enigmático protagonista de "Classroom of the Elite". Estudante do prestigioso Colégio Koudo Ikusei, ele esconde suas habilidades extraordinárias e inteligência sob uma fachada de aluno mediano. Treinado na secreta "Sala Branca", Ayanokouji é um estrategista brilhante e manipulador astuto. Sua personalidade calma e reservada esconde sua verdadeira natureza e um passado misterioso, revelado aos poucos à medida que ele protege e influencia seus colegas de classe.', 
            'Suzune Horikita é uma das principais personagens de "Classroom of the Elite". Aluna do prestigioso Colégio Koudo Ikusei, ela é conhecida por sua inteligência afiada e determinação inabalável. Horikita mantém uma postura fria e distante, concentrando-se exclusivamente em seus objetivos acadêmicos. Sua ambição é alcançar a Classe A, e ela raramente se desvia desse caminho. Com o tempo, Horikita revela camadas mais profundas de sua personalidade, mostrando uma dedicação sincera aos amigos e um desejo de entender melhor os outros, especialmente seu enigmático colega, Kiyotaka Ayanokouji.', 
            'Kushida Kikyo é uma personagem central em "Classroom of the Elite". Aluna do prestigiado Colégio Koudo Ikusei, ela é conhecida por seu comportamento amigável e sociável, mas esconde uma natureza manipuladora. Apesar de sua fachada de bondade e popularidade, Kushida tem um lado obscuro que busca controlar e sabotar os outros para alcançar seus próprios objetivos. Sua habilidade em manter uma imagem de perfeição torna difícil para os colegas perceberem sua verdadeira intenção até que seus segredos sejam revelados.', 
            'Karuizawa Kei é uma figura importante em "Classroom of the Elite". Estudante do renomado Colégio Koudo Ikusei, ela é conhecida por sua beleza e charme, mas também por sua personalidade complexa. Karuizawa é frequentemente vista como uma jovem elegante e popular, mas sua aparência atraente oculta uma profunda insegurança e um passado difícil. Sua luta interna e suas estratégias para manter sua posição social revelam uma faceta mais vulnerável e humana, contrastando com sua imagem pública.'
        ],
        "color_personagem": [
            "rgba(124, 1, 0, 0.9) 0%, rgba(200, 50, 50, 0.9) 50%, rgba(124, 1, 0, 0.9) 100% ", 
            "rgba(0, 51, 102, 0.9) 0%, rgba(51, 102, 153, 0.9) 50%, rgba(0, 51, 102, 0.9) 100%", 
            "rgba(255, 182, 193, 0.9) 0%, rgba(255, 105, 180, 0.9) 50%, rgba(255, 182, 193, 0.9) 100%", 
            "rgba(255, 223, 204, 0.9) 0%, rgba(255, 140, 105, 0.9) 50%, rgba(255, 223, 204, 0.9) 100%"
        ],
    },
    "Bocchi The Rock": {
        "nome_personagem": ['Gotoh Hitori', 'Nijika Ijichi', 'Ikuyo Kita', 'Ryo Yamada'],
        "img_personagem": [
            "midias/image/Bocchi-the-rock/Gotoh_Hitori.png",
            "midias/image/Bocchi-the-rock/Nijika.png",
            "midias/image/Bocchi-the-rock/Kita-chan.png",
            "midias/image/Bocchi-the-rock/Ryo.png"
        ],
        "texto_personagem": [
            'Gotoh Hitori é a protagonista introspectiva de "Bocchi the Rock!". Estudante do segundo ano, ela busca se destacar na escola através da música e se destaca como uma guitarrista talentosa. Com um passado marcado por inseguranças e dificuldades sociais, Hitori usa a música como uma forma de expressão e fuga. Sua jornada é uma mistura de desafios pessoais e crescimento, onde sua habilidade com a guitarra é um reflexo de sua evolução e luta por aceitação.', 
            'Nijika Ijichi é a animada e otimista baterista de "Bocchi the Rock!". Ela é uma colega de banda de Gotoh e possui um espírito energético que contrasta com a personalidade mais reservada de Hitori. Nijika tem um profundo amor pela música e uma atitude positiva que ilumina o ambiente ao seu redor. Apesar das dificuldades, sua paixão pela bateria e seu desejo de criar música com seus amigos a tornam uma peça fundamental na banda e uma fonte constante de motivação.', 
            'Ikuyo Kita é uma das personagens principais da série de mangá e anime, Bocchi the Rock!. Ela está no primeiro ano da Shuka High School e é responsável pela guitarra e vocais da banda, Kessoku Band. Ela começou a admirar Ryo Yamada depois de ver seu show de rua, então ela entrou na Kessuko Band, com a motivação inicial de estar gostando da Ryo Yamada, entretanto, ela começa a compartilhar do amor pela banda e música.', 
            'Ryo Yamada é uma das personagens principais da série de mangá e anime, Bocchi the Rock!. Ela está em seu segundo ano na Shimokitazawa High School e é a baixista da banda, Kessoku Band . Ela trabalha meio período na casa de shows STARRY com Nijika Ijichi .Ela tem uma aparência andrógina e uma atmosfera misteriosa, como silêncio e inexpressividade. Ela frequentemente fascina mulheres, incluindo Ikuyo Kita , que se apaixona à primeira vista. '
        ],
        "color_personagem": [
            "rgba(159, 5, 98, 0.9), rgba(176, 8, 109, 0.9), rgba(176, 8, 109, 0.9), rgba(193, 11, 120, 0.9), rgba(226, 16, 142, 0.9)", 
            "rgba(255, 200, 50, 0.9) 0%, rgba(255, 255, 100, 0.9) 50%, rgba(255, 200, 50, 0.9) 100%", 
            "rgba(255, 0, 0, 0.9) 0%, rgba(255, 100, 100, 0.9) 50%, rgba(255, 0, 0, 0.9) 100%",
            "rgba(0, 100, 200, 0.9) 0%, rgba(100, 150, 255, 0.9) 50%, rgba(0, 100, 200, 0.9) 100%"
            
        ],
    },
    "Kimetsu No Yaiba": {
        "nome_personagem": ['Tanjiro Kamado', 'Zenitsu Agatsuma', 'Inosuke Hashibira', 'Kyojuro Rengoku', 'Tengen Uzui', 'Giyu Tomioka', 'Muichiro Tokito', 'Obanai Iguro', 'Mitsuri', 'Shinobu', 'Nezuko Kamado'],
        "img_personagem": [
            "midias/image/Kimetsu no Yaiba/Tanjiro.png",
            "midias/image/Kimetsu no Yaiba/Zenistu.png",
            "midias/image/Kimetsu no Yaiba/Inosuki.png",
            "midias/image/Kimetsu no Yaiba/Rengoku.png",
            "midias/image/Kimetsu no Yaiba/Tengen.png",
            "midias/image/Kimetsu no Yaiba/Giyu.png",
            "midias/image/Kimetsu no Yaiba/Muichiro.png",
            "midias/image/Kimetsu no Yaiba/Obanai.png",
            "midias/image/Kimetsu no Yaiba/Mitsuri.png",
            "midias/image/Kimetsu no Yaiba/Shinobu.png",
            "midias/image/Kimetsu no Yaiba/Nezuko.png",
        ],
        "texto_personagem": [
            'Tanjiro Kamado é o protagonista principal de Demon Slayer: Kimetsu no Yaiba . Ele é um Caçador de Demônios na Demon Slayer Corps que se juntou para encontrar um remédio para transformar sua irmã, Nezuko Kamado, de volta em humana e para caçar e matardemônios, e mais tarde jurou derrotarMuzan Kibutsuji, o Rei dos Demônios, a fim de evitar que outros sofressem o mesmo destino que ele. Antes de se tornar um Matador de Demônios, Tanjiro era um queimador de carvão antes de sua família ser massacrada por Muzan, enquanto sua irmã mais nova, Nezuko , foi transformada em um demônio.',
            'Zenitsu é um espadachim incrivelmente talentoso, exibindo proficiência altamente refinada em esgrima extremamente rápida como Iaijutsu e na técnica Thunderclap e Flash , a ponto de poder criar ramificações da técnica e utilizá-la mesmo enquanto dorme. Desde o início, Zenitsu parece um Matador de Demônios talentoso e habilidoso, embora ele negue isso. Sua força desperta quando ele está dormindo, pois seu comportamento nervoso é o que normalmente o impede de acessar suas habilidades, tornando-o mais sagaz, calmo e preciso em combate.',
            'Inosuke Hashibira é um dos personagens principais de Demon Slayer: Kimetsu no Yaiba e, junto com Zenitsu Agatsuma, é um companheiro de viagem de Tanjiro Kamadoe Nezuko Kamado. Inosuke é um espadachim muito habilidoso e talentoso, pois ele foi capaz de aprender a Respiração de Concentração Total por conta própria, desenvolver seu próprio Estilo de Respiração conhecido como Respiração da Besta com base em seus próprios instintos e criação nas montanhas por javalis, e passar na Seleção Final para se tornar um Matador de Demônios, tudo sem treinamento formal.',
            'Como um Hashira do Demon Slayer Corps, Kyojuro era um combatente muito poderoso e habilidoso. Antes de tomar o lugar de seu pai, Kyojuro já havia se mostrado um lutador incrível.  Kyojuro foi um dos espadachins mais poderosos e habilidosos de toda a organização. Além disso, Kyojuro faz parte da família Rengoku, que tem uma linhagem impressionante de poderosos espadachins e Flame Hashira, dando a Kyojuro uma vantagem no desenvolvimento e polimento de sua esgrima. Sua extraordinária habilidade com a espada foi exibida em várias ocasiões ao longo da série.',
            'Tengen Uzui nasceu em uma família de nove filhos dentro de um clã shinobi. Três dos nove filhos morreram antes mesmo de completarem 10 anos. Eles foram então forçados a se matar sem saber com quem lutavam, pois suas cabeças e rostos estavam cobertos com máscaras. Seu pai os forçou a passar por um treinamento severo e intensivo como uma tentativa de salvar o clã, e os influenciou a acreditar que precisavam dispor de vidas inocentes para seu benefício, e apenas ter uma esposa como meio de produzir descendentes. Tengen ficou horrorizado e decidiu deixar o clã com suas três esposas.',
            'Giyu Tomioka é um personagem coadjuvante importante de Kimetsu no Yaiba . Ele é um Demon Slayer do Demon Slayer Corps e o atual Water Hashira .Ele cresceu ao lado de sua irmã mais velha. Quando ele ainda era criança, sua irmã se sacrificou para protegê-lo dos demônios. Giyu tentou contar aos outros sobre isso, no entanto, ele foi rotulado como doente mental e foi enviado para um de seus parentes, um médico. Ele fugiu e quase morreu em uma montanha, mas foi resgatado por Sakonji Urokodaki, que o treinaria.',
            'Muichiro Tokito e seu irmão gêmeo, Yuichiro, eram filhos de um lenhador. Após a morte de sua mãe e do pai em um acidente, Amane Ubuyashiki tentou recrutar os gêmeos para a Corporação de Caçadores de Demônios, mas foi rejeitado por Yuichiro. No verão seguinte, um Demônio atacou e feriu gravemente Yuichiro, que acabou morrendo. Muichiro destruiu o Demônio e, após perder suas memórias, uniu-se ao Demon Slayer Corps, tornando-se Hashira em dois meses.',
            'Obanai Iguro é um personagem coadjuvante importante de Kimetsu no Yaiba . Ele é um Demon Slayer do Demon Slayer Corps e o atual Serpent Hashira. É um dos espadachins mais fortes e habilidosos de todo o Demon Slayer Corps. Pode enfrentar oponentes com mais de um século de experiência em combate. Foi quem ensinou todos os outros Demon Slayers na revisão de espadas do Demon Slayer Corps. Pode fazer uma espada de madeira normal dobrar, tecer e estender de maneiras impossíveis. Deve ser comparável a Sanemi e Giyu . Criou seu próprio estilo de respiração que fazia uso de uma arma única',
            'Mitsuri Kanroji mostrou força sobrenatural desde jovem e tinha uma cor de cabelo incomum, o que levou a ser vista como uma aberração e a rejeição de um casamento planejado aos dezessete anos. Para se adaptar, ela tingiu o cabelo de preto e se forçou a viver normalmente. No entanto, ao encontrar Kagaya Ubuyashiki, que a encorajou a aceitar sua verdadeira força como um presente, Mitsuri se tornou a Love Hashira do Demon Slayer Corps.',
            'Shinobu Kocho foi criada em uma casa amorosa e atenciosa até que seus pais foram massacrados por Demônios bem diante dos olhos dela e de sua irmã mais velha Kanae. Quando o Demônio estava prestes a tirar a vida dela e de sua irmã também, elas foram salvas por Gyomei Himejima que matou o Demônio. Depois que isso aconteceu, Shinobu e Kanae prometeram se tornar Caçadoras de Demônios para proteger uma à outra, bem como evitar que outras pessoas sofressem as mesmas perdas que elas tiveram que experimentar.',
            'Nezuko é a irmã mais nova de Tanjiro Kamado e a deuteragonista de Kimetsu no Yaiba . Ela foi transformada em um demônio por Muzan Kibutsuji depois que ele massacrou sua família. Porém, mesmo após se tornar um demônio ele não matou nenhum humano, lutando contra sua natureza enquanto salva humanos e ajuda tanjiro em suas lutas, até que por fim, possam achar uma cura para tornala humana novamente.',
        ],
        "color_personagem": [
            "rgba(30, 60, 150, 0.9) 0%, rgba(60, 100, 200, 0.9) 50%, rgba(30, 60, 150, 0.9) 100%",
            "rgba(255, 220, 80, 0.9) 0%, rgba(255, 200, 90, 0.9) 25%, rgba(255, 180, 40, 0.9) 50%, rgba(255, 160, 50, 0.9) 75%, rgba(255, 220, 80, 0.9) 100%",
            "rgba(150, 90, 80, 0.9) 0%, rgba(200, 120, 100, 0.9) 50%, rgba(150, 90, 80, 0.9) 100%",
            "rgba(255, 80, 30, 0.9) 0%, rgba(255, 140, 70, 0.9) 50%, rgba(255, 80, 30, 0.9) 100%",
            "rgba(124, 1, 0, 0.9) 0%, rgba(200, 50, 50, 0.9) 50%, rgba(124, 1, 0, 0.9) 100%",
            "rgba(9, 159, 179, 0.856) 0%, rgba(19, 227, 255, 0.856) 25%,rgba(11, 192, 216, 0.856) 50%, rgba(9, 159, 179, 0.856) 100%",
            "rgba(1, 81, 105, 0.9) 0%, rgba(0, 120, 156, 0.9) 25%,rgba(0, 96, 126, 0.9) 50%,rgba(1, 81, 105, 0.9) 100%",
            "rgba(196, 236, 15, 0.9) 0%, rgba(19, 31, 199, 0.9) 50%, rgba(196, 236, 15, 0.9) 100%",
            "rgba(187, 71, 181, 0.9) 0%, rgba(202, 51, 195, 0.9) 50%, rgba(223, 39, 213, 0.9) 100%",
            "rgba(162, 12, 221, 0.9) 0%, rgba(164, 32, 216, 0.9)  50%,rgba(181, 58, 230, 0.9) 100%",
            "rgba(211, 7, 126, 0.9) 0%,rgba(211, 7, 68, 0.9)  50%,rgba(199, 37, 86, 0.9) 100%"
        ],
    },
    "Oshi no Ko": {
        "nome_personagem": ['Aqua Hoshino', 'Ai Hoshino', 'Ruby Hoshino', 'Arima Kana'],
        "img_personagem": [
            "midias/image/Oshi no ko/Aqua_Hoshino.png",
            "midias/image/Oshi no ko/hoshino_ai.png",
            "midias/image/Oshi no ko/Ruby.png",
            "midias/image/Oshi no ko/Arima_kana.png"
        ],
        "texto_personagem": [
            'Água Hoshino, nome completo, Aquamarine Hoshino ou mais comumente conhecido apenas como Aqua, é o protagonista masculino e um dos personagens titulares de Oshi no Ko . Em sua vida anterior, ele era conhecido como Gorou Amamiya , um médico que foi assassinado por um perseguidor de um de seus pacientes, Ai Hoshino , e reencarnou como filho deste último. Antes da tragédia que atingiu sua família, Aqua era considerado relativamente normal, exceto por seu talento prodigioso incomparável em atuar, mesmo quando criança, e sua sagacidade e inteligência como ler livros complexos.',
            'Ai Hoshino foi a personagem titular e a garota-propaganda de Oshi no Ko . Ela foi a ídolo principal do B-Komachi original e mãe de Aqua Hoshino e Ruby Hoshino. Como ídolo, ela viveu uma vida de enganos fingindo amar genuinamente seus fãs. Depois de engravidar dos gêmeos, para não desperdiçar sua reputação, ela deu à luz e os criou em segredo, desempenhando o papel de ídolo e mãe. No entanto, suas mentiras inevitavelmente a pegaram quando ela foi fatalmente atacada por um fã descontente , usando seus momentos finais para dizer aos filhos que os amava.',
            'Ruby Hoshino, mais comumente referida apenas como Ruby, é a protagonista feminina e uma das personagens titulares de Oshi no Ko . Em sua vida anterior, ela era conhecida como Sarina Tendouji , uma paciente terminal que foi cuidada por Gorou Amamiya e, após sua morte, reencarnou como filha de seu ídolo favorito, Ai Hoshino. Ao contrário de Aqua, que é calma, calculista e discreta, Ruby é o oposto polar dele, pois é extrovertida, extrovertida, barulhenta, otimista e comunicativa em comparação com seu irmão taciturno. ',
            'Kana Arima é uma personagem coadjuvante importante em Oshi no Ko . Ela é uma conhecida de infância de Aqua e Ruby Hoshino e uma atriz infantil prodigiosa, embora sua popularidade tenha diminuído ao longo dos anos. Ela também é o centro do grupo ídolo revivido B-Komachi. Kana é descrita como uma garota diligente e trabalhadora, empática, alegre e confiante, com um impressionante senso de responsabilidade. Ela também pode ser rude e de língua afiada às vezes devido ao seu passado.'
        ],
        "color_personagem": [
           "rgba(0, 150, 255, 0.9) 0%, rgba(0, 120, 230, 0.9) 25%, rgba(0, 100, 200, 0.9) 50%, rgba(0, 80, 170, 0.9) 75%, rgba(0, 150, 255, 0.9) 100%",
           "rgba(255, 180, 200, 0.9) 0%, rgba(255, 150, 190, 0.9) 25%, rgba(255, 120, 160, 0.9) 50%, rgba(255, 100, 140, 0.9) 75%, rgba(255, 180, 200, 0.9) 100%",
           "rgba(255, 70, 70, 0.9) 0%, rgba(255, 130, 50, 0.9) 33%, rgba(255, 180, 40, 0.9) 66%, rgba(255, 70, 70, 0.9) 100%",
           "rgba(120, 30, 50, 0.9) 0%, rgba(150, 50, 70, 0.9) 25%, rgba(180, 70, 90, 0.9) 50%, rgba(150, 50, 70, 0.9) 75%, rgba(120, 30, 50, 0.9) 100%",
        ],
    },
    "Konosuba": {
        "nome_personagem": ['Kazuma', 'Aqua', 'Darkness', 'Megumin'],
        "img_personagem": [
            "midias/image/Konosuba/Kazuma.png",
            "midias/image/Konosuba/Aqua.png",
            "midias/image/Konosuba/Darkness.png",
            "midias/image/Konosuba/Megumin.png"
        ],
        "texto_personagem": [
            'Kazuma Satou, é o protagonista de Konosuba. após morrer ele é guiado para outro mundo pela deusa Aqua, levando ela consigo para esse novo mundo. Quando ele tem dinheiro suficiente para viver confortavelmente, Kazuma não tem vergonha de ser um vagabundo preguiçoso, e certamente agirá como um. Quando todos podem escapar com segurança de uma luta difícil, Kazuma recua mais rápido do que as mulheres. Kazuma pode ser um trabalhador esforçado e um lutador engenhoso, mas ele provavelmente será seu eu pervertido e preguiçoso, a menos que a situação exija.',
            'Aqua é uma das principais protagonistas da série KonoSuba. Antes da vida no Mundo da Fantasia, ela era uma Deusa da Água que guiava os humanos na vida após a morte. Ela é adorada no Mundo da Fantasia pela Ordem de Axis. Ela é uma garota bem chorona que frequentemente reclama, mas pode ficar séria em caso de perigo. Aqua não tem habilidades analíticas básicas e autoconsciência para usar seu conhecimento efetivamente. Sua sorte é tão baixa que constantemente a coloca em situações ruins; pode até mesmo contrariar a sorte de Kazuma e seus próprios buffs.',
            'Darkness vem de uma família rica, sendo uma Cruzado e uma das personagens principais da série Kono Subarashii Sekai ni Shukufuku Wo!. Ela tem uma personalidade masoquista e uma mira horrenda, gerando momentos engraçados e não sendo nenhum pouco adequada para combate um contra um. Apesar de seus pontos fracos, Darkness é uma Cruzado muito forte, ajudando na defesa e sendo uma tanque inestimável tanto para a guilda como para o grupo do Kazuma.',
            'Megumin é uma das personagens principais de Kono Subarashii Sekai ni Shukufuku Wo! Megumin é uma Archwizard e a primeira pessoa a se juntar ao grupo de Kazuma. Sendo um Demônio Carmesim; Megumin possui uma alta estatística mágica que lhe permitiu fazer a classe Archwizard no nível um. No entanto, seu desejo de praticar apenas Magia de Explosão a deixou incapaz de encontrar trabalho até que ela se juntou ao grupo de Kazuma. Os talentos e a personalidade de Megumin conseguem torná-la uma responsabilidade e um ativo valioso.'
        ],
        "color_personagem": [
           "rgba(0, 80, 0, 0.9) 0%, rgba(0, 120, 0, 0.9) 25%, rgba(0, 160, 0, 0.9) 50%, rgba(0, 120, 0, 0.9) 75%, rgba(0, 80, 0, 0.9) 100%",
           "rgba(0, 180, 255, 0.9) 0%, rgba(0, 150, 230, 0.9) 25%, rgba(0, 120, 200, 0.9) 50%, rgba(0, 90, 170, 0.9) 75%, rgba(0, 180, 255, 0.9) 100%",
           "rgba(255, 140, 0, 0.9) 0%, rgba(255, 160, 40, 0.9) 25%, rgba(255, 180, 80, 0.9) 50%, rgba(255, 160, 40, 0.9) 75%, rgba(255, 140, 0, 0.9) 100%",
           "rgba(180, 30, 180, 0.9) 0%, rgba(220, 50, 50, 0.9) 25%, rgba(200, 30, 30, 0.9) 50%, rgba(220, 50, 50, 0.9) 75%, rgba(180, 30, 180, 0.9) 100%"
        ],
    },
    "Isekai de Cheat Skill": {
        "nome_personagem": ['Yuuya Tenjou', 'Kaori Houjou', 'Lexia Von Arselia', 'Miu Midou'],
        "img_personagem": [
            "midias/image/Isekai the cheat skill/Yuuya.png",
            "midias/image/Isekai the cheat skill/Kaori.png",
            "midias/image/Isekai the cheat skill/Lexia.png",
            "midias/image/Isekai the cheat skill/Miu.png"
        ],
        "texto_personagem": [
            'Yuuya Tenjou é o protagonista principal da série. Ele descobriu a porta para outro mundo no quarto secreto de seu avô e pode ir e voltar entre Argena e a Terra. Ele se tornou extraordinário em ambos os mundos. Desde que Yuuya foi discriminado por todos, exceto por seu avô , ele tem um complexo de inferioridade que às vezes o corrói. Por causa disso, ele não tem muita confiança para se defender e é oprimido mesmo se o fizer. Embora ele esteja extremamente arrependido de sua vida de cabeça para baixo, ele nunca deixa de ser uma pessoa gentil.',
            'Kaori Houjou é a filha do presidente do internato Tsukasa Houjou que foi salva por Yuuya Tenjou quando estava sendo assediada por alguns estranhos perto da loja de conveniência. Sentindo-se altamente em dívida com ele, ela o convidou pessoalmente para se tornar um aluno da academia mais prestigiada do Japão, a Academia Ousei . Conforme a história avança, ela se apaixona por ele, embora ainda não tenha percebido. Ela é a primeira terráquea trazida por Yuuya para viajar para outro mundo.',
            'Lexia Von Arselia, é a primeira princesa do Reino Arselian . Durante sua escolta, ela foi emboscada por um grupo misterioso, que pretendia matá-la. Enquanto ela estava encurralada por eles, um general goblin matou o grupo e estava prestes a matá-la, mas Yuuya a salvou, mais tarde ela desmaiou na cena. Isso também a fez se apaixonar por ele à primeira vista. Lexia é uma garota extremamente extrovertida que diz o que quer que esteja em sua mente sem rodeios e agudamente ciente de que às vezes ela pode parecer mimada, mas ela se defende geralmente dizendo que é a Primeira Princesa.',
            'Miu Midou, é uma modelo popular na Star Productions que fez parceria com Yuuya Tenjou para uma sessão de fotos porque seu antigo parceiro designado, Shou, estava atrasado e acabou sendo demitido pelo gerente da Star Productions por negligência e assédio. Miu conheceu Yuuya no shopping. Eles se tornaram parceiros modelos designados para fotos de "Namorado e Namorada". Miu desenvolveu um sentimento romântico por Yuuya e estava disposta a fazer qualquer coisa para que Yuuya finalmente fosse aceita como modelo pela Star Productions.'
        ],
        "color_personagem": [
           "rgba(0, 0, 0, 0.9) 0%, rgba(50, 20, 20, 0.9) 25%, rgba(100, 40, 40, 0.9) 50%, rgba(50, 20, 20, 0.9) 75%, rgba(0, 0, 0, 0.9) 100%",
           "rgba(0, 0, 0, 0.9) 0%, rgba(50, 20, 20, 0.9) 25%, rgba(100, 40, 40, 0.9) 50%, rgba(50, 20, 20, 0.9) 75%, rgba(0, 0, 0, 0.9) 100%",
           "rgba(200, 120, 80, 0.9) 0%, rgba(240, 150, 90, 0.9) 25%, rgba(255, 180, 120, 0.9) 50%, rgba(240, 150, 90, 0.9) 75%, rgba(200, 120, 80, 0.9) 100%",
           "rgba(100, 60, 30, 0.9) 0%, rgba(140, 90, 60, 0.9) 25%, rgba(180, 120, 90, 0.9) 50%, rgba(140, 90, 60, 0.9) 75%, rgba(100, 60, 30, 0.9) 100%"
        ],
    },
}
